config/routes.rb
Rails.application.routes.draw do
  root "courses#index" 
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  resources :rooms do
      resources :messages
  end

  get 'courses/mycourse'
  resources :enrollments, only: [:index]
  get 'enrollments/showquiz/:lecture_id', to: 'enrollments#showquiz', as: :showquiz

  resources :courses do
      get 'enroll', to: 'enrollments#create'
      get 'mylecture', to: 'lectures#mylecture'
      resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
      end
  end
  
  resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
      resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
  end

      # devise_for :users, :controllers => {registrations: 'registrations'}
    # resources :users, :controllers => {registrations: 'registrations'}

    #devise_for :users, :controllers => {registrations: 'registrations'}, path: 'users'

    devise_for :users, path: '', path_names: {
       sign_in: 'login',
      #session: 'login',
      sign_out: 'logout',
      registration: 'signup',
      confirmation: 'confirm'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmation: 'users/confirmations'
    }

  namespace :api do
    namespace :v1 do
      resources :courses do
        get 'mycourses'
        get 'enroll', to: 'enrollments#create'
        get 'mylecture', to: 'lectures#mylecture'
        resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
        end
      end
      resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
        resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
    end
    end
  end
  
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :quiz
	validates :content, presence: true
	#has_many :answers, dependent: :destroy
	#accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  before_action :set_quiz
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @questions = @quiz.questions
    render json: @questions
  end

  def create
    @question = @quiz.questions.build(question_params)
    authorize! :manage, @question

    if @question.save
      render json: { message: 'Question successfully created.' }
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @question = @quiz.questions.find(params[:id])
    authorize! :manage, @question

    if @question.update(question_params)
      render json: { message: 'Question successfully updated.' }
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @question = @quiz.questions.find(params[:id])
    authorize! :manage, @question

    if @question.destroy
      render json: { message: 'Question successfully destroyed.' }
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def question_params
    params.require(:question).permit(:content, :answer1, :answer2, :answer3, :answer4, :correct)
  end

  def set_quiz
    @quiz = Quiz.find(params[:quiz_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question
  def index
    @questions = @quiz.questions 
    @lecture=@quiz.lecture
    @course=@lecture.course
    #authorize! :manage, @question

  end

  def destroy
    @question=@quiz.questions.find(params[:id])
    authorize! :manage, @question
    @question.destroy
    redirect_to quiz_questions_path(@quiz), notice: "Question was successfully Destroyed."
  end

  def new
    @question=@quiz.questions.new
    @lecture=@quiz.lecture
    @course=@lecture.course 
  end

  def create
    @lecture=@quiz.lecture
    @course=@lecture.course
    @question=@quiz.questions.create(question_params)
    authorize! :manage, @question
    if @question.save
      #redirect_to quiz_questions_path(@quiz), notice: 'Question Successfully created'
      redirect_to course_lecture_myquiz_path(@course,@lecture), notice: 'Question Successfully created'
      
    else
      render :new
    end
  end

  def edit
    @question=@quiz.questions.find(params[:id])
    @lecture=@quiz.lecture
    @course=@lecture.course
  end

  def update
    @question=@quiz.questions.find(params[:id])
    authorize! :manage, @question
    if @question.update(question_params)
      redirect_to quiz_questions_path(@quiz), notice: "Question was successfully updated."
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  private

  def question_params
    params.require(:question).permit(:quiz_id, :content, :answer1, :answer2, :answer3, :answer4, :correct )
  end
  def set_question
    @quiz= Quiz.find(params[:quiz_id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question_fields.html.erb
<div style="text-align: center;">
  <div style="display: inline-block; background-color: #f0f0f0; padding: 20px;">
  <br>
  <%= form_with(model: [quiz, @question], local: true) do |form| %>
    <div class="question">
      <%= form.label :content, "Enter Question" %>
      <%= form.text_area :content %>
      <br><br>
      <% 1.upto(4) do |i| %>
        <%= form.label "answer#{i}", "Option #{i}" %>
        <%= form.text_field "answer#{i}", class: "form-control mb-3" %> <br>
      <% end %>

      <%= form.label :correct, "Correct Answer" %>
      <%= form.select :correct, (1..4).to_a, {}, class: "form-control mb-3" %>
      <br><br>
      <%= form.submit 'Create Question', style: "background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;" %>
    </div>
  <%end %>
  </div>
</div>

<div class="content" style="display: inline-block; margin-left: 10px;">
  <%= link_to "Back to Lectures", course_mylecture_path(@course), class: 'btn btn-secondary' %>
</div> 

<div class="content" style="display: inline-block; margin-left: 10px;">
  <%#= link_to "Back to All Question", quiz_questions_path(quiz), class: 'btn btn-secondary' %>
</div> 

app/views/questions/edit.html.erb
<br>
<center><h1 style="font-weight: bold; margin: 50px;">Update Question</h1></center>

<div id="questions">
  <%= render 'question_fields', quiz: @quiz, question: @question, course: @course %>
</div>

app/views/questions/index.html.erb
<div class="content" style="display: inline-block; margin-left: 10px;">
<h2>All Questions for :- <%= @quiz.title %> </h2>

  <% @questions.each do |q| %>
    <div class="question-box" style="display: inline-block; margin-left: 10px; border: 1px solid black; padding: 10px;">
    <h6> Question :- <%= q.content %><br></h6>
    <h6>Option 1 :- <%= q.answer1 %><br><h6>
    <h6>Option 2 :- <%= q.answer2 %><br><h6>
    <h6>Option 3 :- <%= q.answer3 %><br><h6>
    <h6>Option 4 :- <%= q.answer4 %><br><h6>
    <h6>Correct_Answer :- <%= q.correct %><br><h6>
    </div>    
  <% end %>
  <br> <br>

  <div class="content" style="display: inline-block; margin-left: 10px;">
    <%#= link_to "Add New Quetion", new_quiz_question_path(@quiz.id), class: 'btn btn-secondary' %>
  </div> 
  <div class="content" style="display: inline-block; margin-left: 10px;">
    <%= link_to "Back to Enrolled course ", enrollments_path, class: 'btn btn-secondary' %>
  </div>
  <div class="content" style="display: inline-block; margin-left: 10px;">
    <%#= link_to "Back to Enrolled Course ", enrollments_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/questions/new.html.erb
<center><h1 style="font-weight: bold;">Create New Question</h1></center>

<div id="questions">
  <%= render 'question_fields', quiz: @quiz, question: @question, course: @course %>
</div>