config/routes.rb
Rails.application.routes.draw do
  root "courses#index" 
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  resources :rooms do
      resources :messages
  end

  get 'courses/mycourse'
  resources :enrollments, only: [:index]
  get 'enrollments/showquiz/:lecture_id', to: 'enrollments#showquiz', as: :showquiz

  resources :courses do
      get 'enroll', to: 'enrollments#create'
      get 'mylecture', to: 'lectures#mylecture'
      resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
      end
  end
  
  resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
      resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
  end

      # devise_for :users, :controllers => {registrations: 'registrations'}
    # resources :users, :controllers => {registrations: 'registrations'}

    #devise_for :users, :controllers => {registrations: 'registrations'}, path: 'users'

    devise_for :users, path: '', path_names: {
       sign_in: 'login',
      #session: 'login',
      sign_out: 'logout',
      registration: 'signup',
      confirmation: 'confirm'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmation: 'users/confirmations'
    }

  namespace :api do
    namespace :v1 do
      resources :courses do
        get 'mycourses'
        get 'enroll', to: 'enrollments#create'
        get 'mylecture', to: 'lectures#mylecture'
        resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
        end
      end
      resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
        resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
    end
    end
  end
  
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :video, presence: { message: 'must be attached' }
  has_one_attached :video
  has_one :quiz, dependent: :destroy
  
  #accepts_nested_attributes_for :quiz

  #validate :validate_video_format

  # def validate_video_format
  #   return unless video.attached?

  #   unless video.content_type.in?(%w[video/mp4 video/mov video/avi])
  #     errors.add(:video, 'must be in MP4, MOV, or AVI format')
  #   end
  # end

end

app/controllers/api/v1/lectures_controller.rb
class Api::V1::LecturesController < ApplicationController
  before_action :set_course
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @lectures = @course.lectures
    render json: @lectures
  end

  def create
    @lecture = @course.lectures.build(lecture_params)
    @lecture.user = current_user

    if @lecture.save
      # render json: { message: 'Lecture was successfully created.' }
      render json: @lecture, status: :created
    else
      render json: { errors: @lecture.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @lecture = @course.lectures.find(params[:id])

    if @lecture.update(lecture_params)
      render json: { message: 'Lecture was successfully updated.' }
    else
      render json: { errors: @lecture.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @lecture = @course.lectures.find(params[:id])
    @quiz = @lecture.quiz
    render json: { lecture: @lecture, quiz: @quiz }
  end

  def destroy
    @lecture = @course.lectures.find(params[:id])
    @lecture.destroy
    render json: { message: 'Lecture was successfully destroyed.' }
  end

  def mylecture
    @lectures= @course.lectures
    render json: {lectures: @lectures}
  end


  private

  def lecture_params
    params.require(:lecture).permit(:video)
  end

  def set_course
    @course = Course.find(params[:course_id])
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_course
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @lectures= @course.lectures
  end

  def new
    @lecture=@course.lectures.build
  end

  def create
    @lecture=@course.lectures.build(lecture_params)
    @lecture.user = current_user
    if @lecture.save
      # redirect_to course_lectures_path(@course), notice: 'Lecture was successfully created .'
      redirect_to course_mylecture_path, notice: "Lecture was successfully created."
    else
      render :new
    end
  end

  def edit
    @lecture = @course.lectures.find(params[:id])
  end

  def update
    @lecture = @course.lectures.find(params[:id])
    if @lecture.update(lecture_params)
      # redirect_to course_lectures_path(@course), notice: "Lecture was successfully updated."
      redirect_to course_mylecture_path, notice: "Lecture was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def show
    @lecture = @course.lectures.find(params[:id])
    @quiz = @lecture.quiz
  end

  def destroy
    @lecture = @course.lectures.find(params[:id])
    @lecture.destroy
    redirect_to course_lectures_path(@course), notice: "Lecture was successfully destroyed."    
  
  end

  def mylecture
    @lectures= @course.lectures
  
  end

  private
  def lecture_params
    params.require(:lecture).permit(:video)
  end
  def set_course
    @course = Course.find(params[:course_id])
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/edit.html.erb
<h1>Update Lecture</h1>

<%= form_with(model: [@course, @lecture], local: true) do |form| %>  
  <%= form.label :video %>
  <%= form.file_field :video,  disposition: 'attachment' %>
<%= form.submit 'Update Lecture' %>
<% end %>

<%= link_to 'Back to Lectures', course_mylecture_path %>

app/views/lectures/index.html.erb
<%= notice %>
<% @lectures.each do |lecture|%>
  <% if lecture.video.attached? %>
    <p>Download File: <%= link_to lecture.video.filename, rails_blob_path(lecture.video,disposition: 'attachment') %></p>
  <% end %>
<%end%>

<%= link_to 'Back to Course', courses_mycourse_path %>  <br><br>
<%= link_to 'Add New Lecture', new_course_lecture_path(@course) %>

app/views/lectures/mylecture.html.erb
<% @lectures.each do |lecture|%>
  <% if lecture.video.attached? %>
    <p>Download Video: <%= link_to lecture.video.filename, rails_blob_path(lecture.video,disposition: 'attachment') %></p>
    
  <div class="content" style="display: inline-block; margin-left: 200px;">
    <p>
    <strong>Update Lectures</strong><br/>
    <small><%= link_to 'Update Lecture', edit_course_lecture_path(@course,lecture), class: 'btn btn-secondary' %></small>
    </p>
  </div>

  <div class="content" style="display: inline-block; margin-left: 200px;">
    <p>
    <strong>Delete Lectures</strong><br/>
    <small><%= button_to "Delete Lecture", course_lecture_path(@course, lecture), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></small>
    </p>
  </div>

  <div class="content" style="display: inline-block; margin-left: 200px;">
    <p>
      <center><strong>Quiz For this lecture<strong></center><br/>
      <strong><%= link_to 'Create Quizz ', new_course_lecture_quiz_path(@course, lecture), class: 'btn btn-secondary'%><strong>
    </p>
  </div>

  <div class="content" style="display: inline-block; margin-left: 20px;">
    <p>
      <strong><%= link_to 'Show Quizz', course_lecture_myquiz_path(@course,lecture), class: 'btn btn-secondary' %></strong>
    </p>
  </div>
    
  <%end%>
<%end%>
<br>

<div class="content" style="display: inline-block; margin-left: 10px;">
  <%= link_to "Back to Courses", courses_mycourse_path, class: 'btn btn-secondary' %>
</div>

app/views/lectures/new.html.erb
<h1>Add New Lecture</h1>

<%= form_with(model: [@course, @lecture], local: true) do |form| %>
  <%= form.label :video %>
  <%= form.file_field :video,  disposition: 'attachment' %>
  <% @lecture.errors.full_messages_for(:video).each do |message| %>
    <p class="text-danger"><%= message %></p>
  <% end %>

<%= form.submit 'Create Lecture' %>
<% end %>

<%= link_to 'Back to Lectures', course_lectures_path(@course) %>

app/views/lectures/show.html.erb
<%= notice %>
<% if @quiz.present? %>
  <h2> Quiz: <%= @quiz.title %></h2>
  <% @quiz.questions.each do |question| %>
    <p><strong>Question:</strong> <%= question.content %></p>
  <% end %>
<% else %>
  <p>No quiz available for this lecture.</p>
<% end %>

<div class="content" style="display: inline-block; margin-left: 10px;">
  <%= link_to "Back to Lectures", course_lectures_path(@course), class: 'btn btn-secondary' %>
</div> 