config/routes.rb
Rails.application.routes.draw do
  root "courses#index" 
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  resources :rooms do
      resources :messages
  end

  get 'courses/mycourse'
  resources :enrollments, only: [:index]
  get 'enrollments/showquiz/:lecture_id', to: 'enrollments#showquiz', as: :showquiz

  resources :courses do
      get 'enroll', to: 'enrollments#create'
      get 'mylecture', to: 'lectures#mylecture'
      resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
      end
  end
  
  resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
      resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
  end

      # devise_for :users, :controllers => {registrations: 'registrations'}
    # resources :users, :controllers => {registrations: 'registrations'}

    #devise_for :users, :controllers => {registrations: 'registrations'}, path: 'users'

    devise_for :users, path: '', path_names: {
       sign_in: 'login',
      #session: 'login',
      sign_out: 'logout',
      registration: 'signup',
      confirmation: 'confirm'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmation: 'users/confirmations'
    }

  namespace :api do
    namespace :v1 do
      resources :courses do
        get 'mycourses'
        get 'enroll', to: 'enrollments#create'
        get 'mylecture', to: 'lectures#mylecture'
        resources :lectures do
          get 'myquiz', to: 'quizzes#myquiz'
          resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy]
        end
      end
      resources :quizzes, only: [:new,:create,:show,:edit,:update,:destroy] do
        resources :questions, only: [:new, :index, :create,:show,:edit,:update,:destroy]
    end
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.role == 'Instructor'
      can :manage, Course, user_id: user.id
      can :manage, Lecture
      can :manage, Quiz
      can :manage, Question
      can :manage, Room
    elsif user.role == 'Student'
      can :read, Course
      can :read, Lecture
      can :read, Quiz
      can :read, Question
      can :read, Room
    else
      can :read, Course
      can :read, Lecture
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :enrollments, dependent: :destroy
  has_many :lectures, dependent: :destroy
  has_many_attached :documents, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 100}
  validates :documents, presence: true

  scope :enrolled_by_student, -> (student_id) { joins(:enrollments).where(enrollments: {user_id: student_id} ) }

  #private

  #  def check_file_type
  #   if documents.attached? && !documents.content_type.in?(%i(application/pdf))
  #     documents.purge # delete the uploaded file
  #     errors.add(:documents, 'Must be a PDF or a DOC file')
  #   end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
    
  validates :user_id, uniqueness: { scope: :course_id, message: "has already enrolled in this course" }
  
  default_scope { order(enrollment_date: :asc) }
  
end

app/models/instructor.rb
class Instructor < User
    
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :video, presence: { message: 'must be attached' }
  has_one_attached :video
  has_one :quiz, dependent: :destroy
  
  #accepts_nested_attributes_for :quiz

  #validate :validate_video_format

  # def validate_video_format
  #   return unless video.attached?

  #   unless video.content_type.in?(%w[video/mp4 video/mov video/avi])
  #     errors.add(:video, 'must be in MP4, MOV, or AVI format')
  #   end
  # end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  after_create_commit { broadcast_append_to self.room }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :enrollment
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :quiz
	validates :content, presence: true
	#has_many :answers, dependent: :destroy
	#accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	belongs_to :lecture
	has_many :questions, dependent: :destroy
	#accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  validates :title, presence: {message: "Title cant be blank ..."}, length: { maximum: 100 }
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> {where(is_private: false)}
  after_create_commit {broadcast_append_to "rooms"}
  has_many :messages
end

app/models/student.rb
class Student < User
  #self.inheritance_column = :type

end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: self


  enum role: {Instructor: 0, Student: 1}


  has_many :enrollments, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :lectures, dependent: :destroy
  has_many :messages, dependent: :destroy

  scope :all_except, ->(user) { where.not(id: user) }
  #after_create_commit { broadcast_append_to "users" }
  
  scope :by_role, -> (role) { where(role: role) }

  validates :name, presence: true
  validates :username, presence: true 


  serialize :attempted_quizzes, Array
    
  def quiz_attempted?(quiz)
    attempted_quizzes.include?(quiz.id)
  end

  def mark_quiz_attempted(quiz)
    attempted_quizzes << quiz.id
    save
  end

  def jwt_payload
    super
  end
end

app/controllers/api/v1/enrollments_controller.rb
class Api::V1::EnrollmentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @enrollments = current_user.enrollments
    render json: @enrollments
  end

  def create
    @course = Course.find(params[:course_id])
    @enrollment = current_user.enrollments.build(course: @course, enrollment_date: Date.today)
    
    if @enrollment.save
      render json: { message: 'Successfully enrolled in the course.' }
    else
      render json: { error: 'You are already enrolled in this course.' }, status: :unprocessable_entity
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @enrollments =current_user.enrollments
    @courses = Course.enrolled_by_student(current_user.id)
    #@courses=Course.joins(:enrollments).where("enrollments.user_id = ?",current_user.id)
  end

  def new
    @course = Course.find(params[:course_id])
    @enrollment =Enrollment.new
  end

  def create
    @course = Course.find(params[:course_id])
    #if Enrollment.pluck(:course_id).include?(@course.id) && Enrollment.pluck(:user_id).include?(current_user.id)
    @enrollment = current_user.enrollments.build(course: @course, enrollment_date: Date.today)
    if @enrollment.save
      redirect_to @course, notice: 'Successfully enrolled in the course.'
    else
      redirect_to course_path(@course), alert: 'You are already enrolled in this course .'
    end
  end

  def show
    @enrollment=Enrollment.find(params[:id])  
  end

  def showquiz
    @lecture = Lecture.find(params[:lecture_id])
  end

  private

  def enroll_params
    params.require(:enrollment).permit(:course_id,:user_id)
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  include ApplicationHelper
    
  def total_enrolled_students(course)
    course.enrollments.count
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
  def enrolled?(student_id)
    Enrollment.exists?(user_id: student_id)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/enrollments/index.html.erb
<br>
<%= link_to 'Back', courses_path, class: "btn btn-secondary" %>


<% if enrolled?(current_user.id) %>
  <% @courses.each do |enrollment| %>
    <div class="course-box" style="background-color: #f0f0f0; padding: 20px; margin: 10px;">
      <h1 class="card-title">Course Title: <%= enrollment.title %></h1>
      <p><strong class="card-text">Description:</strong> <%= enrollment.description %></p>

      <% if enrollment.documents.attached? %>
        <p><strong>Download Documents:</strong></p>
        <ul>
        <% enrollment.documents.each do |document| %>
          <li><%= link_to document.filename, rails_blob_path(document) %></li>  
        <% end %>
        </ul>
      <% end %>

      <% if enrollment.lectures.any? %>
        <strong>Lectures:</strong>
        <div class="lecture-list">
          <% enrollment.lectures.each do |lecture| %>
            <div class="lecture-box" style="background-color: #f9f9f9; padding: 10px; margin: 10px;">
            <h3><%#= lecture.title %></h3>
            <% if lecture.video.attached? %>
              <p><strong>Lecture Video:</strong> <%= link_to lecture.video.filename, rails_blob_path(lecture.video, disposition: 'attachment') %></p>
            <% end %>
            <% if lecture.quiz.present? %>
              <div class="quiz-link">
              <% if current_user.quiz_attempted?(lecture.quiz) %>
                <p>You have attempted the quiz for this lecture.</p>
              <%else%>
                <%= link_to 'Start Quiz', showquiz_path(lecture), class: "btn btn-secondary", notice: 'Quiz Submitted successfully!!!!!!' %>
                <%# current_user.mark_quiz_attempted(lecture.quiz) %>
              <%end%>
              </div>
            <% end %> 
            </div>
          <% end %>
        </div>    
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>No enrollments for this course yet.</p>
<% end %>

app/views/enrollments/show.html.erb
<div class="container">
  <div class="row mt-3">
  <div class="col-md-8 offset-md-2">
      <div class="card">
      <div class="card-body">
        <h1 class="card-title"><%= @course.title %></h1>
        <p class="card-text">Description: <%= @course.description %></p>
          <% if @course.documents.attached? %>
              <% @course.documents.each do |document| %>
                <p>Download File: <%= link_to document.filename, rails_blob_path(document) %></p>    
              <%end%>
          <% else %>
              <p>No file attached.</p>
          <% end %>
          
          <% if @course.lectures.any? %>
              <% @course.lectures.each do |lecture|%>
                  <% if lecture.video.attached? %>
                      <p>Download Video: <%= link_to lecture.video.filename, rails_blob_path(lecture.video,disposition: 'attachment') %></p>
                  <%end%>
              <%end%>
          <%end%>
          
          <% if current_user && current_user.role=='Student' %>
              <% if @course.enrollments.where("user_id = ?",current_user.id)%>
                  <p>You are already enrolled in this course since <%= @course.enrollments.find_by(user_id: current_user.id).enrollment_date.strftime("%Y-%m-%d") %>.</p>
              <% else %>
                  <%= link_to 'Enroll in this course', enroll_course_path(@course), method: :post %>
              <% end %>
          <% end %>
      
          <a href="#" class="btn btn-primary">View Course</a>
          <%= link_to 'Back', courses_path, class: "btn btn-secondary" %>
      </div>
      </div>
  </div>
  </div>
</div>

app/views/enrollments/showquiz.html.erb
<%= notice%>
<h2>Quiz Topic: <%= @lecture.quiz.title %></h2>
<%= form_tag quiz_questions_path(@lecture.quiz), method: :get, id: "quiz-form", class: "quiz-form" do %>
<% @lecture.quiz.questions.each do |question| %>
<div style="background-color: #fff; border: 1px solid #ccc; padding: 10px; margin: 10px;">
<p><strong>Question: <%= question.content %></strong></p>
<%= hidden_field_tag 'questions[]', question.id %>
<p><label><%= radio_button_tag "#{question.id}", question.answer1 %>(a) <%= question.answer1 %></label></p>
<p><label><%= radio_button_tag "#{question.id}", question.answer2 %>(b) <%= question.answer2 %></label></p> 
<p><label><%= radio_button_tag "#{question.id}", question.answer3 %>(c) <%= question.answer3 %></label></p>
<p><label><%= radio_button_tag "#{question.id}", question.answer4 %>(d) <%= question.answer4 %></label></p>
</div>
<% end %>
<%= submit_tag 'Submit Answers', class: 'btn btn-primary', id: 'submit-button', enable: true %>
<%end%>

<div id="error-message" style="color: red; margin: 10px; display: none;">
Please select an answer for all questions before submitting the quiz.
</div>

<script>
document.getElementById('submit-button').addEventListener('click', function(event) {
const selectedAnswers = document.querySelectorAll('input[type="radio"]:checked');
const totalQuestions = <%= @lecture.quiz.questions.count %>;

if (selectedAnswers.length < totalQuestions) {
event.preventDefault(); // Prevent form submission
document.getElementById('error-message').style.display = 'block'; }
});
</script>